### ISSUE TITLE
What does TagOverflowDefense do?

### ISSUE THREAD

**Issue by SaiVK** [cla7aye15I4nd/shadowbound#14]
Hello
  I was going through the OverflowDefense pass source code. What does TagOverflowDefense do? Any pointers.
Also, does ShadowBound currently work for stack variables and globals?

Thanks
Sai

**Comment by cla7aye15I4nd** [comment]
Apologies for the delayed response. The TagOverflowDefense feature has been deprecated, and Shadowbound no longer supports stack and global usage. If you have any further questions about the implementation, please feel free to email me, as I check my emails more regularly than the issues.
