### ISSUE TITLE
Inquiry About Shadow Memory and Buffer Bound Tracking

### ISSUE THREAD

**Issue by Ryuanxue** [cla7aye15I4nd/shadowbound#15]
Hello, 

I am currently exploring your tool and have learned that it employs a shadow memory-based metadata management mechanism to store heap chunk boundaries. I am particularly interested in the capability to track the base and bounds of the buffers pointed to by pointers.

Could you please let me know if your tool can provide this information? Additionally, what steps would be necessary to obtain the base and bound information, and what modifications would be required to the existing code? Any insights or suggestions you could offer would be greatly appreciated.

Thank you for your assistance. I look forward to your response.

Best regards,
xue rao

**Comment by cla7aye15I4nd** [comment]
Yes, shadowbound can provide these information. About concrete steps. you can refer my papers. If you want to know more impl detals, please email me (see dataisland.org), we can discuss privately.
